#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
        echo "Bringing up network..."
        /etc/netup
        /usr/sbin/inetd
        ;;
  stop)
        echo -n "Bringing down network..."
        echo "TODO"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
